### PR TITLE
Support Koa v2

### PR DESCRIPTION
**Pull request by omsmith**
Was just in the neighbourhood and thought I'd poke at it.

### CODE REVIEW

**Comment by tejasmanohar** [comment]
@omsmith How does / will [this](https://github.com/omsmith/route/blob/koa2/index.js#L35) work since neither rest/spread are in Node 4.x.x without flags, [right](https://nodejs.org/en/docs/es6/)? I may be missing something.

```
.../node_modules/koa-route/index.js:35
        return Promise.resolve(fn(ctx, ...args, next));
                                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../index.js:6:22)
    at Module._compile (module.js:434:26)
```

**Comment by omsmith** [comment]
Right. Koa has needed flags for so long it didn't seem like a big deal, but this probably isn't worthwhile as the feature to cause it.

Easily switched back to building the array

**Comment by tejasmanohar** [comment]
@omsmith Would you provide an example that works with this?

**Comment by omsmith** [comment]
@tejasmanohar Good call. Updated the example in the README, and the (identical) example.js

**Comment by tejasmanohar** [comment]
Thanks man! Well, +1 from me on this PR. Thoughts, @jonathanong?

**Comment by jonathanong** [comment]
LGTM

**Comment by tejasmanohar** [comment]
@jonathanong Fine if I merge and release v3.0 on GH then? I think I'll need access to NPM to actually push it though (... [npm-org-rights](https://github.com/repo-utils/npm-org-rights)) :)

**Comment by jonathanong** [comment]
when in doubt, ask @koajs/owners!

**Comment by tejasmanohar** [comment]
reviewed some more, seems fine. don't really have any questions / doubts

**Pull request merged**
