### PR TITLE
Add support for prefixing

### PR DESCRIPTION
**Pull request by PaulAvery**
Hi, so today I realised, that I would love to define prefixes for sets of routes.
This PR therefore allows for the following:

``` js
var _ = require('koa-route');
// Lets create a prefix
var api = _('/api');

// We can nest prefixes if we want to
var v1 = api('/v1');

// Or define them directly
var v2 = _('/api/v2');

// /api/v1/some/route
koa.use(v1.get('/some/route', route));

// /api/v1/some/:parameterized/route
koa.use(v1.get('/some/:parameterized/route', route));

// /api/v2
koa.use(v2.all(route));

// /api/v2/
koa.use(v2.all('/', route));

// This still works
koa.use(_.get('/some/view', view));
```

I hope this change does not increase the scope of this module too much for your taste.
I changed the readme and example.js as well as the tests, to acommondate the new feature.
I am not sure about the way I restructured the tests though, I just ran all of them twice, once with a prefix and one without.

Please let me know if you like the idea, and if neccessary, which changes would need to be made to land this PR.

### CODE REVIEW

**Comment by PaulAvery** [comment]
Any feedbacks on this? Otherwise I just publish my version as `@paulavery/koa-route` and use it from there.

**Comment by hallas** [comment]
Hi! Sorry about that. Let us look it over for a few more days ok?

However chances are we will not accept feature changes for this module but lets see.

Sorry we missed it!

**Comment by PaulAvery** [comment]
No problem, thanks for the response.
I am happy to wait now that I know someone actually saw this :)

**Comment by tejasmanohar** [comment]
I kinda like this feature overall- need some more time to review implementation / tests though.

@hallas - thoughts?

**Comment by simplyianm** [comment]
:+1: i really like this feature

**Comment by coderhaoxin** [comment]
@PaulAvery can you rebase this PR?

**Comment by SEAPUNK** [comment]
Why not https://github.com/koajs/mount ?

**Comment by jeromemacias** [comment]
+1 for using koa-mount

**Pull request closed without merging**
