### PR TITLE
Next

### PR DESCRIPTION
**Pull request by tejasmanohar**
remove github flag

### CODE REVIEW

**Comment by tj** [comment]
peerDependencies :D

**Comment by tejasmanohar** [comment]
@tj hm? are some peer deps missing?

**Comment by tj** [comment]
just seeing lots of people getting confused about which versions of middleware are for which Koa, but peerDependencies lets you specify that

**Comment by tejasmanohar** [comment]
ah, i see. hm yea, guess we could set those tho they won't take effect in npm 3. should be a good warning for a user installing them. i also think we should add a notice to all of the readme's or at least the one in koajs/koa. what do you think? @tj 

i can add stuff tmrw

**Comment by tj** [comment]
oh really? I swear it has been around for a few years, that should alleviate the need for docs/manual installs

**Pull request closed without merging**
